name: hydrated_state_notifier_hive
description: An extension to the state_notifier library which automatically persists and restores state_notifier states.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: ^2.0.0
  synchronized: ^3.0.0
  meta: ^1.3.0
  hydrated_state_notifier:
    path: ../hydrated_state_notifier

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  collection: ^1.15.0
  crypto: ^3.0.0
  freezed_annotation: ^0.15.0
  freezed: ^0.15.0+1
  json_serializable: ^6.0.0
  json_annotation: ^4.3.0
  mocktail: ^0.3.0
  path: ^1.8.0
  uuid: ^3.0.0
