name: example
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/predatorx7/hydrated_state_notifier/tree/main/packages/hydrated_state_notifier/example
publish_to: 'none'

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  hydrated_state_notifier:
    path: ../
  hydrated_state_notifier_hive:
    path: ../../hydrated_state_notifier_hive
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
