name: hydrated_state_notifier

on:
  push:
  pull_request:
  schedule:
    # runs the CI every first day of every month at 00:00 AM
    - cron: "0 0 1 * *"

jobs:
  dart:
    runs-on: ubuntu-latest
    container: dart:${{ matrix.channel }}

    strategy:
      matrix:
        package:
          - packages/hydrated_state_notifier
          - packages/hydrated_state_notifier_hive
        channel:
          - latest
          - beta

    steps:
      - uses: actions/checkout@v3

      # It is executed separatly
      - name: Removing example folder
        run: rm -rf example
        working-directory: ${{ matrix.package }}

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ matrix.package }}

      - name: Check format
        run: dart format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: dart analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: dart test --coverage coverage --test-randomize-ordering-seed=random
        working-directory: ${{ matrix.package }}

      - name: Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: ${{ matrix.package }}/coverage/lcov.info

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pana:
    runs-on: ubuntu-latest
    container: dart:${{ matrix.channel }}

    strategy:
      matrix:
        package:
          - packages/hydrated_state_notifier
          - packages/hydrated_state_notifier_hive
        channel:
          - latest
          - beta

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          dart pub get
          dart pub global activate pana
        working-directory: ${{ matrix.package }}
      - name: Verify Pub Score
        run: ../../scripts/verify_pub_score.sh 110
        working-directory: ${{ matrix.package }}
