name: hydrated_state_notifier

on:
  push:
  pull_request:
  schedule:
    # runs the CI every first day of every month at 00:00 AM
    - cron: "0 0 1 * *"

jobs:
  dart:
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.channel }}

    strategy:
      matrix:
        package:
          - packages/hydrated_state_notifier
          - packages/hydrated_state_notifier_hive
        channel:
          - dev
          # latest is stable release
          - beta

    steps:
      - uses: actions/checkout@v2

      # It is executed separatly
      - name: Removing example folder
        run: rm -rf example
        working-directory: ${{ matrix.package }}

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ matrix.package }}

      - name: Check format
        run: dart format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: dart analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: dart test --coverage coverage --test-randomize-ordering-seed=random
        working-directory: ${{ matrix.package }}

      - name: Coverage
        run: dart run coverage:format_coverage -l -i ./coverage/test/state_notifier_test.dart.vm.json -o ./coverage/lcov.info --packages ./.packages
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - packages/hydrated_state_notifier
          - packages/hydrated_state_notifier/example
          - packages/hydrated_state_notifier_hive
          - packages/hydrated_state_notifier_hive/example
        channel:
          - dev
          - beta

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      # It is executed separatly
      - name: Removing example folder
        run: rm -rf example
        working-directory: ${{ matrix.package }}

      - name: Override dependencies
        run: ./scripts/setup_dependencies.sh

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Check format
        run: flutter format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage --test-randomize-ordering-seed=random
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1

  pana:
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.channel }}

    strategy:
      matrix:
        package:
          - packages/hydrated_state_notifier
          - packages/hydrated_state_notifier_hive
        channel:
          - dev
          # latest is stable release
          - beta

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          dart pub get
          dart pub global activate pana
      - name: Verify Pub Score
        run: ../../scripts/verify_pub_score.sh 110
        working-directory: ${{ matrix.package }}
